GET http://localhost:3000/

###
GET http://localhost:3000/todo/1693812317161
###

DELETE http://localhost:3000/todo/1697121052422

###

POST http://localhost:3000/todo
Content-Type: application/json

{
    "data": "ini datanya",
    "keterangan": "Keterangan"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username":"notaris1",
    "password":"n0t4r1s"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyMTY1YmEyLTZiZDQtNDgyYS05NWMxLWU3ZWMyZDkyMzFkZiIsImlhdCI6MTY5NzQ2ODk4NywiZXhwIjoxNjk3NTU1Mzg3fQ.EhQhLrCMzYwPfLxYzpGW6X-Yl4i_XddfU0IXiatlMU8"
}
###

GET http://localhost:3000/api/kondite/9b4e1e94-8bb9-4dd3-bf7e-5a7ba7909cc4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyMTY1YmEyLTZiZDQtNDgyYS05NWMxLWU3ZWMyZDkyMzFkZiIsIm5hbWEiOiJOb3RhcmlzIDEiLCJ1c2VybmFtZSI6Im5vdGFyaXMxIiwicm9sZSI6WyJub3RhcmlzIl0sImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2OTc0Njg5ODcsImV4cCI6MTY5NzQ3MDc4N30.5O4MtZKTBsR-1-NW27jH8tENnyfxdJvLduoSWca3EXI

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nama":"SuperUser 2",
    "username":"su2",
    "password":"susususu",
    "role":["mpd","mpw","mpp"]
}

###
POST http://localhost:3000/api/kondite/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyMTY1YmEyLTZiZDQtNDgyYS05NWMxLWU3ZWMyZDkyMzFkZiIsIm5hbWEiOiJOb3RhcmlzIDEiLCJ1c2VybmFtZSI6Im5vdGFyaXMxIiwicm9sZSI6WyJub3RhcmlzIl0sImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2OTc0NjcxNTksImV4cCI6MTY5NzQ2ODk1OX0.cR3J1MOp6PPnSZbMJfurKKTSnmpq7ovTzYf4v4qZtdw

{
  "jenisLayanan": "Sample Service",
  "kodeVoucher": "ABC1234",
  "skPengangkatanPindah": {
    "nomorSurat": "SK123",
    "tanggalSurat": "2023-10-13 00:00:00",
    "file" : ""
  },
  "beritaAcaraSumpah": {
    "nomorSurat": "BA1234",
    "tanggalSurat": "2023-10-13 00:00:00",  
    "file": "ba123.pdf"
  },
  "suratPernyataanPemegangProtokol": {
    "nomorSurat": "SPP1234",
    "tanggalSurat": "2023-10-13 00:00:00", 
    "file": "spp123.pdf"
  },
  "suratPernyataanJumlahAktaNotaris": {
    "nomorSurat": "SPP1234",
    "tanggalSurat": "2023-10-13 00:00:00", 
    "file": "spp123.pdf",
    "jumlahAktaDisahkan": 10,
    "jumlahAktaDibutuhkan": 20
  }
}


###
PUT http://localhost:3000/kondite/7a72695d-c60d-487c-90cd-2c921c789f86
Content-Type: application/json

{
  "jenisLayanan": "Sample Service2"
}
